version: '3.9'

services:
  frontend:
    container_name: frontend
    build:
      context: ./front
    env_file:
      - .env
#   dev
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "8081:8081"
    command: npm run serve
    depends_on:
      - backend
    restart: always
  backend:
    container_name: backend
    build:
      context: ./backend
    env_file:
      - .env
#   dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5001:5001"
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:14.2
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
#      - ./db:/docker-entrypoint-initdb.d
    restart: always
  nginx:
    image: nginx:1.20.2
    container_name: nginx
    restart: always
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
volumes:
  pgdata: